api = "https://registry.pesde.daimond113.com"
github_oauth_client_id = "a1d648966fdfbdcd9295"
wally_allowed = ["https://github.com/UpliftGames/wally-index"]
other_registries_allowed = ["https://github.com/daimond113/pesde-index"]
scripts_packages = ["pesde/scripts_rojo"]
